// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersAPI.Models;

#nullable disable

namespace UsersAPI.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UsersAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Christopher.Oberbrunner@yahoo.com",
                            Name = "Christopher Oberbrunner",
                            Password = "w7Do_cyuIM"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Curtis_Kiehn@gmail.com",
                            Name = "Curtis Kiehn",
                            Password = "CtR_rIe8TJ"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Katherine.Nicolas98@hotmail.com",
                            Name = "Katherine Nicolas",
                            Password = "jq3YVJhcMD"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Kristen74@hotmail.com",
                            Name = "Kristen Beer",
                            Password = "KIMQu93UGg"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Lindsey_Wilderman58@gmail.com",
                            Name = "Lindsey Wilderman",
                            Password = "gOqLT4Sjc5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Corey.Bins63@yahoo.com",
                            Name = "Corey Bins",
                            Password = "oelOJReOfO"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Beatrice71@hotmail.com",
                            Name = "Beatrice Metz",
                            Password = "EnOGqmwReX"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Kayla_Smith@gmail.com",
                            Name = "Kayla Smith",
                            Password = "VlW4V06kIE"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Sophia_Buckridge74@yahoo.com",
                            Name = "Sophia Buckridge",
                            Password = "7k03JmDQ2d"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Roman_Kovacek3@hotmail.com",
                            Name = "Roman Kovacek",
                            Password = "bkoTbUCUsn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
